default_platform(:ios)

# --------------------------------------------------------------------------
# iOS
# --------------------------------------------------------------------------
platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :metadata do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_IDENTIFIER"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
    )

    deliver(
      api_key: api_key,
      skip_binary_upload: true,
      skip_screenshots: false,
      force: true,                  # Skip HTML preview
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
    )
  end
end

# --------------------------------------------------------------------------
# Android
# --------------------------------------------------------------------------
platform :android do
  desc "Upload metadata and screenshots to Google Play"
  lane :metadata do
    upload_to_play_store(
      json_key_data: ENV["GCLOUD_SERVICE_ACCOUNT_CREDENTIALS"],
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
    )
  end
end
